" General:
" --------
" ~/.vimrc
" To reload, run `:source ~/.vimrc` or `source %`
" Contents:
" - Default Settings:
" - Key Bindings:
" - Status Bar:
" - FZF:
" - Languages:
" - Python:
" - Bash:
" - Plugins:
" -
" -

" Default Settings:
" -----------------
set relativenumber number " Relative lines with absolute line number at cursor.
set nowrap                " Do not wrap long lines.
set encoding=utf-8
set hidden                " Allows to switch buffers without saving.
set smartcase
set splitright            " When splitting window, new window appears to the right.


" Key Bindings:
" -------------
" Split navigations
" nnoremap <C-J> <C-W><C-J>
" nnoremap <C-K> <C-W><C-K>
" nnoremap <C-L> <C-W><C-L>
" nnoremap <C-H> <C-W><C-H>

" Buffer switching
nnoremap <C-k> :bn<CR>
nnoremap <C-j> :bp<CR>
nnoremap <C-x> :bd<CR>

" Increment with <C-i>
" nn <C-i> <C-a>

" Enable folding with spacebar
" nnoremap <space> za


" Status Bar:
" -----------
" Show status line
set laststatus=2
function! GitBranch()
    return system("git rev-parse --abbrev-ref HEAD 2>/dev/null | tr -d '\n'")
endfunction

function! StatuslineGit()
    let l:branchname = GitBranch()
    return strlen(l:branchname) > 0?'  '.l:branchname.' ':''
endfunction

set statusline=
set statusline+=%#PmenuSel#
set statusline+=%{StatuslineGit()}
set statusline+=%#LineNr#
set statusline+=\ %f
set statusline+=%m\
set statusline+=%=
set statusline+=%#CursorColumn#
set statusline+=\ %y
" set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
" set statusline+=\[%{&fileformat}]
set statusline+=\ %p%%
set statusline+=\ %l:%c\|%L
" set statusline+=\ %L%*               "total line
" set statusline+=%*%L%*               "total line
" set statusline+=\


" FZF:
" ----
set nocompatible            "Fuzzy search only current project
set path+=**                "Include subdirectories
set wildmenu                "Press tab to enter wild menu

" Highlight trailing white spaces
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
" More on white spaces
set list!
if has('gui_running')
	set listchars=tab:▶\ ,trail:·,extends:\#,nbsp:.
else
	set listchars=tab:>.,trail:.,extends:\#,nbsp:.
"	set listchars=tab:▶\ ,trail:·,extends:\#,nbsp:.
endif


" Languages:
" ----------
" General
set tabstop=4
set shiftwidth=4
set expandtab

" Taskfiles
autocmd BufRead,BufNewFile *askfile set syntax=yaml

" JavaScript
autocmd BufNewFile,BufRead *.js, *.html, *.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2


" Python:
" -------
autocmd BufNewFile,BufRead *.py
    \ set foldmethod=indent |
    \ set foldlevel=99 |
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |
    \ set textwidth=99


" Bash:
" -----
autocmd BufNewFile,BufRead *.sh
    \ set noexpandtab |
    \ set syntax=bash


" Plugins:
" --------
" vimawesome.com: that's where I ususaly find plugins.
"
" VimPlug: The minimalistic plugin manager.
" -----------------------------------------
" * Installation:
"     curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
" * vimrc:
"   In ~/.vimrc insert `Plug` commands between `call plug#begin` and `call
"   plug#end
"
" * Commands:
"   - PlugInstall [name] [#threads]
"   - PlugUpdate [name] [#threads]
"   - PlugClean[!]
"   - PlugStatus
"   - PlugDiff

call plug#begin('~/.vim/plugged')
    " FZF: Fuzzy finder
    " -----------------
    "
    " PlugUpdate fzf
    " Basic Usage:
    " * <C-J> or <C-K> move cursor
    " * <tab> select item
    "
    " Syntax:
    " * ' exact
    " * ^ $ begin, end
    " * ! invert
    " * | or
    " * <space> andj
    "
    " Env:
    " * FZF_DEFAULT_COMMAND='fd --type f'
    " * FZF_DEFAULT_OPTIONS="--layout=reversed --inline-info"
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
    nnoremap <silent> <C-f> :Files<CR>

    " Hacky way to make rg not search file names!
    command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".shellescape(<q-args>), 1, {'options': '--delimiter : --nth 4..'}, <bang>0)
    " grep for text in files
    nnoremap <silent> <Space>f :Rg<CR>
    " Optional remaps from fzf.vim
    nnoremap <silent> <Space>b :Buffers<CR>
    nnoremap <silent> <Space>/ :BLines<CR>
    " nnoremap <silent> <Leader>' :Marks<CR>
    " nnoremap <silent> <Leader>g :Commits<CR>
    " nnoremap <silent> <Leader>H :Helptags<CR>
    " nnoremap <silent> <Leader>hh :History<CR>
    " nnoremap <silent> <Leader>h: :History:<CR>
    " nnoremap <silent> <Leader>h/ :History/<CR> 

    " Syntastic: Syntax checking
    " --------------------------
    Plug 'scrooloose/syntastic'
    let g:syntastic_python_checkers=['flake8']
    " set statusline+=%#warningmsg#
    " set statusline+=%{SyntasticStatuslineFlag()}
    " set statusline+=%*

    " let g:syntastic_always_populate_loc_list = 1
    " let g:syntastic_auto_loc_list = 1
    let g:syntastic_check_on_open = 1
    let g:syntastic_check_on_wq = 0

    " Jedi: Code analysis for Python
    " ------------------------------
    Plug 'davidhalter/jedi-vim'

    " Rainbow: Bracket pair colorizer
    " -------------------------------
    Plug 'luochen1990/rainbow'
    let g:rainbow_active = 1

    " Indentpython: Deactivated for now
    " Plug 'vim-scripts/indentpython.vim'

    " YouCompleteMe: Code auto-completion
    " -----------------------------------
    Plug 'Valloric/YouCompleteMe'
    " Let clangd fully control code completion
    let g:ycm_clangd_uses_ycmd_caching = 0
    " Use installed clangd, not YCM-bundled clangd which doesn't get updates.
    let g:ycm_clangd_binary_path = exepath("clangd")

    " GitBlame: Git tools for vim
    " ---------------------------
    Plug 'zivyangll/git-blame.vim'
    nnoremap <Space>s :<C-u>call gitblame#echo()<CR>

    " Syntax: Various syntax colorization definitions
    " -----------------------------------------------
    Plug 'flazz/vim-colorschemes'
    Plug 'vhdirk/vim-cmake'
    Plug 'octol/vim-cpp-enhanced-highlight'
    Plug 'mfukar/robotframework-vim'
call plug#end()

colorscheme molokai
syntax on
